### ISSUE TITLE
Can you please share the code for the frontend as well?

### ISSUE THREAD

**Issue by sensor-projekt** [ThomasVitale/cloud-native-spring-in-action#22]
I really appreciate your book and have found it super informative. I worked along with it when you had the frontend integrated into the edge-service and was wondering if you could now share the frontend as you have separated the two for comparison. Thank you.

**Comment by ThomasVitale** [comment]
@sensor-projekt thank you for your feedback, I'm glad you liked the book! The source code for the frontend will be included in this repository in the final version, which should be really soon. For now, it's available in this separate repository: https://github.com/PolarBookshop/polar-ui

**Comment by sensor-projekt** [comment]
Thank you so much 🙏
