### ISSUE TITLE
spring boot 3

### ISSUE THREAD

**Issue by maku** [ThomasVitale/cloud-native-spring-in-action#28]
Guess the book uses spring boot 2 right? Will there be an update to spring boot 3?

**Comment by ThomasVitale** [comment]
Thanks for your question, @maku. The book uses Spring Boot 2.7. I maintain [a separate branch](https://github.com/ThomasVitale/cloud-native-spring-in-action/tree/sb-3-main) with all the code samples from the book upgraded to Spring Boot 3.0. There are only a few minor changes described [here](https://github.com/ThomasVitale/cloud-native-spring-in-action/blob/sb-3-main/README.md). Keeping those few things in mind (mostly about new naming strategies), the book content applies equally well to Spring Boot 3.0.
