### ISSUE TITLE
Chapter 12 - end. Flyway SQL files without flyway dependency in gradle/pom file

### ISSUE THREAD

**Issue by ahmedkhabkhab** [ThomasVitale/cloud-native-spring-in-action#37]
In [Chapter-12 end](https://github.com/ThomasVitale/cloud-native-spring-in-action/tree/main/Chapter12/12-end/catalog-service/src/main/resources/db/migration). There are 3 versions but the gradle.build/pom.xml doesn't include any flyway dependency. Am I missing something here?

**Comment by ahmedkhabkhab** [comment]
Update: to solve the problem, I added flyway core as a runtime dependency
```
<dependency>
  <groupId>org.flywaydb</groupId>
  <artifactId>flyway-core</artifactId>
  <scope>runtime</scope>
</dependency>
```

if you're using gradle just add this line to dependencies:

`runtimeOnly 'org.flywaydb:flyway-core'`

**Comment by ThomasVitale** [comment]
@ahmedkhabkhab the Flyway dependency is part of the `build.gradle` file already: https://github.com/ThomasVitale/cloud-native-spring-in-action/blob/main/Chapter12/12-end/catalog-service/build.gradle#L37. Did you encounter issues when running the Gradle example in the repo?
