### ISSUE TITLE
ArgoCD LoadBalancer not provisioning

### ISSUE THREAD

**Issue by jempitman** [ThomasVitale/cloud-native-spring-in-action#48]
Hi,

I am having an issue with deployment of ArgoCD in Digital Ocean from the shell script (polar-deployment/kubernetes/platform/production/argocd/deploy.sh), as the External-IP for the LoadBalancer simply does not become available, even if it is left for hours to be provisioned. After checking the logs of the argocd-server pod, it seems that the activity stops after adding an RBAC ConfigMap, which is then followed by a status check every 10 minutes:

argocd % kubectl -n argocd get service argocd-server          
NAME            TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
argocd-server   LoadBalancer   10.245.186.28   80:31173/TCP,443:30104/TCP   22m

argocd % kubectl -n argocd get pods                           
NAME                                                READY   STATUS    RESTARTS   AGE
argocd-application-controller-0                     1/1     Running   0          23m
argocd-applicationset-controller-57f8479986-xkrb6   1/1     Running   0          23m
argocd-dex-server-b57ffc474-hfrqz                   1/1     Running   0          23m
argocd-notifications-controller-585d496999-wrggh    1/1     Running   0          23m
argocd-redis-948ff45c8-kwdm2                        1/1     Running   0          23m
argocd-repo-server-5dbccb487c-8nr2m                 1/1     Running   0          23m
argocd-server-976589cdf-bmfqb                       1/1     Running   0          23m

argocd % kubectl -n argocd logs argocd-server-976589cdf-bmfqb 
time="2023-04-28T08:50:56Z" level=info msg="Starting configmap/secret informers"
time="2023-04-28T08:50:56Z" level=info msg="Configmap/secret informer synced"
time="2023-04-28T08:50:56Z" level=info msg="Initialized server signature"
time="2023-04-28T08:50:56Z" level=info msg="Initialized admin password"
time="2023-04-28T08:50:56Z" level=info msg="Starting configmap/secret informers"
time="2023-04-28T08:50:56Z" level=info msg="secrets informer cancelled"
time="2023-04-28T08:50:56Z" level=info msg="configmap informer cancelled"
time="2023-04-28T08:50:56Z" level=info msg="Configmap/secret informer synced"
time="2023-04-28T08:50:56Z" level=info msg="Initialized TLS certificate"
time="2023-04-28T08:50:56Z" level=info msg="Starting configmap/secret informers"
time="2023-04-28T08:50:56Z" level=info msg="secrets informer cancelled"
time="2023-04-28T08:50:56Z" level=info msg="configmap informer cancelled"
time="2023-04-28T08:50:56Z" level=info msg="Configmap/secret informer synced"
time="2023-04-28T08:50:56Z" level=info msg="argocd v2.4.15+05acf7a serving on port 8080 (url: , tls: true, namespace: argocd, sso: false)"
time="2023-04-28T08:50:56Z" level=info msg="0xc00106c9c0 subscribed to settings updates"
time="2023-04-28T08:50:56Z" level=info msg="Starting rbac config informer"
time="2023-04-28T08:50:56Z" level=info msg="RBAC ConfigMap 'argocd-rbac-cm' added"
time="2023-04-28T09:00:56Z" level=info msg="Alloc=10172 TotalAlloc=29323 Sys=28497 NumGC=9 Goroutines=74"
time="2023-04-28T09:10:56Z" level=info msg="Alloc=10177 TotalAlloc=33411 Sys=28497 NumGC=14 Goroutines=74"
time="2023-04-28T09:20:56Z" level=info msg="Alloc=10185 TotalAlloc=37573 Sys=28497 NumGC=19 Goroutines=74"

I've tried substituting the argo-cd manifest version from gitHub in the argocd/resources/kustomization.yml with 'stable' (as recommended by https://argo-cd.readthedocs.io/en/stable/getting_started/), but I get the same behaviour. 

I don't see what I am missing/ doing wrong as the manifests in the argocd folder are fairly straightforward, the only cause I can think of is that argocd may have a permissions issue within my cluster in Digital Ocean. 

Any ideas or suggestions?

![Screenshot 2023-04-28 at 11 16 52](https://user-images.githubusercontent.com/80392341/235113648-7747bd35-d975-4ac0-824c-779c8f9db069.png)

**Comment by ThomasVitale** [comment]
@jempitman thanks for reporting the issue. Could you share more details about your setup on DigitalOcean so I'll try to reproduce it? What Kubernetes version is the cluster using? (You can check it by running the `doctl k8s cluster get polar-cluster` command.) Was it created following the steps in the book or does it have any additional configuration?

I tried with both the version used in the book and the latest one, and managed to get an external IP address provisioned within 3/4 minutes. My cluster is running version `1.26.3-do.0`.

Thank you!

**Comment by jempitman** [comment]
Thank you for your response, my cluster is also running version 1.26.3-do.0 and was set up without any additional configuration, only using the scripts provided in the PolarBookshop repo.

**Comment by jempitman** [comment]
Support for Digital Ocean has confirmed that a maximum of 2 LoadBalancers can be provisioned on an evaluation/ trial license, so it is not possible to deploy the argocd-server without either removing one of the backing services or waiting until the evaluation period is finished and additional billing history is established.
