### ISSUE TITLE
Typo in polar-deployment/kubernetes/platform/production/keycloak/deploy.sh

### ISSUE THREAD

**Issue by hide1080** [ThomasVitale/cloud-native-spring-in-action#65]
Line 9 of this file looks like this

clientSecret=$(echo $ random | openssl md5 | Head -c 20)

The last Head is supposed to be head.

**Comment by ThomasVitale** [comment]
Thank you for reporting this. I have updated the scripts in https://github.com/ThomasVitale/cloud-native-spring-in-action/commit/449d96a44f74baf70ab831383b8338f565359081
