### ISSUE TITLE
In Chapter 16, provide instructions and code to deploy serverless application quote-function on Knative in the Digital Ocean cloud k8s cluster, not just local minikube

### ISSUE THREAD

**Issue by shantdashjian** [ThomasVitale/cloud-native-spring-in-action#66]
In Chapter 16, you only provide instructions and code to deploy serverless application quote-function locally on Knative on minikube. I would like to see instructions and code to do the next logical step which is to deploy to production using Knative in the Digital Ocean k8s cluster.

**Comment by ThomasVitale** [comment]
@shantdashjian thanks for the suggestion. I have now added a guide to this repo with instructions on how to install a Knative-based platform on a cloud Kubernetes cluster. You can use it for DigitalOcean, but it's really cloud-agnostic, so you can do the same in other cloud providers. https://github.com/ThomasVitale/cloud-native-spring-in-action/commit/9e34b769a040e5a396013aa8e3c445efe26d4ef6

Knative requires a few different components installed in a cluster, so it's not that straightforward to do it from scratch. In the guide, you'll find instructions to use a "platform-in-a-box" setup I use in my personal projects and open-source community work. It's based on [Carvel](https://carvel.dev), a cloud native tool and CNCF project. If you'd like to try it locally first, you can find instructions [here](https://kadras-io.github.io/kadras-docs/docs/getting-started/installation/).

Feel free to reach out should you encounter issues with the setup.
